### ISSUE TITLE
"Release" overhaul

### ISSUE THREAD

**Issue by lfrancke** [theministry/feature-tracker#43]
Currently, releases are treated as dates only.

This has multiple problems:
- If a release slips we'll have to update all features affected by it
- If we mark something as "Completed" it'll immediately show in the unified view with a green checkmark but doesn't distinguish between "already released" and "completed but only available in an upcoming release"
![image](https://user-images.githubusercontent.com/122850/189317965-3a7a4c95-55fa-4ffc-9cf1-99449087c4e3.png)
 One of those two was in a past release, the other one is in an upcoming release
- We can't automatically switch between "Upcoming" and "Released" because the month granularity is not good enoug

Our suggestion would be to treat a Release as a new top-level entity that we can create, update and delete.
A release should have a name, a state ("unreleased", "released") and a release date (optional I guess, at least before the release).

Features can then be attached to a release and their display can update automatically based on whether the release has happened or not.

In the future it might be relevant to attach multiple releases to a single feature but for today a single one is fine.

@sbernauer @maltesander @soenkeliebau Could you please check briefly if this description makes sense to you?

**Comment by soenkeliebau** [comment]
Except for the second bullet point which doesn't parse it makes sense.

> If we mark something as "Completed" but in the feature it'll still get a green checkbox which can be confusing

**Comment by lfrancke** [comment]
I tried to clarify. Does it make more sense now?

**Comment by soenkeliebau** [comment]
yup
