### ISSUE TITLE
Wrong label when creating a new category in Unified mode

### ISSUE THREAD

**Issue by lfrancke** [theministry/feature-tracker#47]
![image](https://user-images.githubusercontent.com/122850/192996838-f49e50ef-3761-4bcf-b8e6-9df4e9536bf5.png)

When I click on a category and there on the "add child" button it is not clear to me whether it's a feature or a category that I'll add.
No matter what I click I see the above which says "Enter feature name", but that doesn't seem to be correct. At least one of them creates a category, maybe both.

I think it makes sense to change
- the mouseover label for the buttons (everywhere basically, the + for adding a feature also only says "add") to say what they are going to create
- fix the placeholder text

**Comment by nikolai-cc** [comment]
Great catch, one of them indeed has the wrong label, and good suggestion! I'll add another issue to check wether if I can improve the mouseover labels throughout the application (especially in the unified view).

**Comment by nikolai-cc** [comment]
N.B. To answer to your confusion in the short term, in the category 'more menu': 'add child' means 'add child category', 'add sibling' means 'add sibling category', in the feature 'more' menu 'add sibling' means 'add sibling feature'.

A category without child features has an empty row to easily add a child feature. I think it might improve UX to have that empty row also for adding child features to categories WITH features, and maybe even to add top-level categories. This will save many menu clicks (and possibly confusion searching for the correct option).

I'll give it a think and improve it when working on this!
